<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use App\Models\Inventory;
use App\Models\InventoryItem;
use App\Models\Product;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (! Schema::hasTable('inventories') || ! Schema::hasTable('inventory_items')) {
            return;
        }

        // Create a single initial inventory record and items based on product stock
        $inventory = Inventory::create([
            'reference_no' => 'INIT-' . now()->format('YmdHis'),
            'type' => 'in',
            'source' => 'Seeder',
            'notes' => 'Initial stock import generated by seeder',
            'inventory_date' => now(),
            'total_modal' => 0,
        ]);

        $total = 0;

        foreach (Product::all() as $product) {
            $qty = (int) $product->stock;
            if ($qty <= 0) {
                continue;
            }

            $cost = $product->cost_price ?? 0;

            InventoryItem::create([
                'inventory_id' => $inventory->id,
                'product_id' => $product->id,
                'quantity' => $qty,
                'cost_price' => $cost,
            ]);

            $total += $qty * $cost;
        }

        $inventory->total_modal = $total;
        $inventory->save();
    }
}
